FROM quay.io/fedora/fedora:44

RUN dnf install -y --setopt=install_weak_deps=False \
        golang hivex perl-hivex jq make guestfs-tools \
        ntfs-3g ntfsprogs && \
    dnf clean all

WORKDIR /workspace/kc-utils
